In [1]:
import mysql.connector as connection
import pandas as pd
import numpy as np

In [2]:
try:
    db = connection.connect(host="localhost", database="DPSB", user="root", password="a21305556699", use_pure=True)
    query = "SELECT Mo, MICL, COUNT(Mo) AS Number, SUM(APA) AS SUM FROM OPERATIONS GROUP BY MO, MICL;"
    df = pd.read_sql(query, db)
    db.close()
except Exception as e:
    db.close()
    print(str(e))

In [3]:
df

         Mo       MICL  Number           SUM
0   CFORETS    Achevée       7  4.151500e+08
1   CFORETS   En cours       3  9.720000e+07
2   CFORETS      Gelée       9  4.065000e+08
3   CFORETS        N L       2  5.900000e+06
4       DAL    Achevée      16  1.597900e+09
5       DAL   En cours       2  1.328720e+09
6       DAL      Gelée       8  3.638000e+09
7       DAS    Achevée       2  1.040000e+07
8      DCOM    Achevée       2  7.500000e+07
9      DCOM      Gelée       1  2.106000e+08
10     DCUL    Achevée       1  1.870000e+08
11     DCUL   En cours       9  1.870400e+09
12     DCUL      Gelée       7  1.068000e+09
13    DENVI  A l'arret       1  1.300000e+08
14    DENVI      Gelée       2  2.800000e+08
15      DEP    Achevée     122  1.334575e+10
16      DEP   En cours      27  1.459755e+10
17      DEP      Gelée      16  5.621500e+09
18      DEP        N L      59  1.037646e+10
19      DEW    Achevée      25  2.719000e+08
20      DEW   En cours      10  4.385000e+08
21      DEW        N L      11  1.481500e+08
22      DFP    Achevée       5  2.730000e+08
23      DFP   En cours       8  1.959625e+09
24      DFP      Gelée      10  1.822000e+09
25      DIM      Gelée       1  5.500000e+07
26      DIM        N L       1  3.000000e+06
27     DIMP    Achevée       3  3.428890e+08
28     DIMP   En cours       1  2.100000e+08
29      DJS  A l'arret       1  3.350000e+08
30      DJS    Achevée       7  5.734560e+08
31      DJS   En cours       2  2.880000e+08
32      DJS      Gelée      28  1.823293e+09
33    DPCIV      Gelée       1  1.200000e+08
34      DRE  A l'arret       2  1.160000e+09
35      DRE    Achevée      20  3.014300e+09
36      DRE   En cours      16  4.455000e+09
37      DRE      Gelée       6  2.290000e+09
38      DRE        N L       2  3.700000e+08
39      DSA   En cours       2  4.950000e+07
40      DSA      Gelée       1  4.600000e+07
41      DSP  A l'arret       2  2.230000e+08
42      DSP    Achevée      19  2.407400e+09
43      DSP   En cours      20  4.459690e+09
44      DSP        N L       4  4.997000e+08
45     DTMA    Achevée       1  7.200000e+07
46     DTMA   En cours       3  5.500000e+08
47     DTMA      Gelée       3  2.650000e+07
48      DTP    Achevée       1  3.000000e+08
49      DTP   En cours       5  3.150000e+09
50      DTR    Achevée       2  9.851670e+08
51      DTR   En cours       1  1.040000e+08
52      DTR      Gelée       3  4.241600e+07
53     DUAC  A l'arret       1  3.000000e+09
54     DUAC    Achevée       1  2.156000e+08
55     DUAC   En cours       2  1.000000e+09
56     DUAC        N L       1  2.000000e+08

In [4]:
res = df.pivot(index="Mo", columns="MICL", values=["Number", "SUM"])

In [5]:
pd.set_option('display.float_format', lambda x: '%.0f' % x)
res = res.replace(np.nan, 0)

In [6]:
res

           Number                                   SUM              \
MICL    A l'arret Achevée En cours Gelée N L  A l'arret     Achevée
Mo
CFORETS         0       7        3     9   2          0   415150000
DAL             0      16        2     8   0          0  1597900000
DAS             0       2        0     0   0          0    10400000
DCOM            0       2        0     1   0          0    75000000
DCUL            0       1        9     7   0          0   187000000
DENVI           1       0        0     2   0  130000000           0
DEP             0     122       27    16  59          0 13345748000
DEW             0      25       10     0  11          0   271900000
DFP             0       5        8    10   0          0   273000000
DIM             0       0        0     1   1          0           0
DIMP            0       3        1     0   0          0   342889000
DJS             1       7        2    28   0  335000000   573456000
DPCIV           0       0        0     1   0          0           0
DRE             2      20       16     6   2 1160000000  3014300000
DSA             0       0        2     1   0          0           0
DSP             2      19       20     0   4  223000000  2407400000
DTMA            0       1        3     3   0          0    72000000
DTP             0       1        5     0   0          0   300000000
DTR             0       2        1     3   0          0   985167000
DUAC            1       1        2     0   1 3000000000   215600000


MICL       En cours      Gelée         N L
Mo
CFORETS    97200000  406500000     5900000
DAL      1328720000 3638000000           0
DAS               0          0           0
DCOM              0  210600000           0
DCUL     1870400000 1068000000           0
DENVI             0  280000000           0
DEP     14597552000 5621500000 10376460000
DEW       438500000          0   148150000
DFP      1959625000 1822000000           0
DIM               0   55000000     3000000
DIMP      210000000          0           0
DJS       288000000 1823293000           0
DPCIV             0  120000000           0
DRE      4455000000 2290000000   370000000
DSA        49500000   46000000           0
DSP      4459690000          0   499700000
DTMA      550000000   26500000           0
DTP      3150000000          0           0
DTR       104000000   42416000           0
DUAC     1000000000          0   200000000

In [7]:
TOTAL_OP = res["Number"].sum(axis=1)
TOTAL_OP.name = "TOTAL OP"
Number = [res["Number"], TOTAL_OP]
Number = pd.concat(Number, axis=1)
Number

         A l'arret  Achevée  En cours  Gelée  N L  TOTAL OP
Mo
CFORETS          0        7         3      9    2        21
DAL              0       16         2      8    0        26
DAS              0        2         0      0    0         2
DCOM             0        2         0      1    0         3
DCUL             0        1         9      7    0        17
DENVI            1        0         0      2    0         3
DEP              0      122        27     16   59       224
DEW              0       25        10      0   11        46
DFP              0        5         8     10    0        23
DIM              0        0         0      1    1         2
DIMP             0        3         1      0    0         4
DJS              1        7         2     28    0        38
DPCIV            0        0         0      1    0         1
DRE              2       20        16      6    2        46
DSA              0        0         2      1    0         3
DSP              2       19        20      0    4        45
DTMA             0        1         3      3    0         7
DTP              0        1         5      0    0         6
DTR              0        2         1      3    0         6
DUAC             1        1         2      0    1         5

In [8]:
TOTAL_SUM = res["SUM"].sum(axis=1)
TOTAL_SUM.name = "SUM"
SUM = [res["SUM"], TOTAL_SUM]
SUM = pd.concat(SUM, axis=1)
SUM

         A l'arret     Achevée    En cours      Gelée         N L         SUM
Mo
CFORETS          0   415150000    97200000  406500000     5900000   924750000
DAL              0  1597900000  1328720000 3638000000           0  6564620000
DAS              0    10400000           0          0           0    10400000
DCOM             0    75000000           0  210600000           0   285600000
DCUL             0   187000000  1870400000 1068000000           0  3125400000
DENVI    130000000           0           0  280000000           0   410000000
DEP              0 13345748000 14597552000 5621500000 10376460000 43941260000
DEW              0   271900000   438500000          0   148150000   858550000
DFP              0   273000000  1959625000 1822000000           0  4054625000
DIM              0           0           0   55000000     3000000    58000000
DIMP             0   342889000   210000000          0           0   552889000
DJS      335000000   573456000   288000000 1823293000           0  3019749000
DPCIV            0           0           0  120000000           0   120000000
DRE     1160000000  3014300000  4455000000 2290000000   370000000 11289300000
DSA              0           0    49500000   46000000           0    95500000
DSP      223000000  2407400000  4459690000          0   499700000  7589790000
DTMA             0    72000000   550000000   26500000           0   648500000
DTP              0   300000000  3150000000          0           0  3450000000
DTR              0   985167000   104000000   42416000           0  1131583000
DUAC    3000000000   215600000  1000000000          0   200000000  4415600000

In [9]:
res = [Number, SUM]
res = pd.concat(res, axis=1)
res

,A l'arret,Achevée,En cours,Gelée,N L,TOTAL OP,A l'arret,Achevée,En cours,Gelée,N L,SUM
Mo,,,,,,,,,,,,
CFORETS,0,7,3,9,2,21,0,415150000,97200000,406500000,5900000,924750000
DAL,0,16,2,8,0,26,0,1597900000,1328720000,3638000000,0,6564620000
DAS,0,2,0,0,0,2,0,10400000,0,0,0,10400000
DCOM,0,2,0,1,0,3,0,75000000,0,210600000,0,285600000
DCUL,0,1,9,7,0,17,0,187000000,1870400000,1068000000,0,3125400000
DENVI,1,0,0,2,0,3,130000000,0,0,280000000,0,410000000
DEP,0,122,27,16,59,224,0,13345748000,14597552000,5621500000,10376460000,43941260000
DEW,0,25,10,0,11,46,0,271900000,438500000,0,148150000,858550000
DFP,0,5,8,10,0,23,0,273000000,1959625000,1822000000,0,4054625000
DIM,0,0,0,1,1,2,0,0,0,55000000,3000000,58000000
DIMP,0,3,1,0,0,4,0,342889000,210000000,0,0,552889000
DJS,1,7,2,28,0,38,335000000,573456000,288000000,1823293000,0,3019749000
DPCIV,0,0,0,1,0,1,0,0,0,120000000,0,120000000
DRE,2,20,16,6,2,46,1160000000,3014300000,4455000000,2290000000,370000000,11289300000
DSA,0,0,2,1,0,3,0,0,49500000,46000000,0,95500000
DSP,2,19,20,0,4,45,223000000,2407400000,4459690000,0,499700000,7589790000
DTMA,0,1,3,3,0,7,0,72000000,550000000,26500000,0,648500000
DTP,0,1,5,0,0,6,0,300000000,3150000000,0,0,3450000000
DTR,0,2,1,3,0,6,0,985167000,104000000,42416000,0,1131583000
DUAC,1,1,2,0,1,5,3000000000,215600000,1000000000,0,200000000,4415600000

In [10]:
TOTAL = res.sum(axis=0)
TOTAL

A l'arret             7
Achevée             234
En cours            111
Gelée                96
N L                  80
TOTAL OP            528
A l'arret    4848000000
Achevée     24086910000
En cours    34558187000
Gelée       17449809000
N L         11603210000
SUM         92546116000
dtype: float64

In [11]:
TOTAL.name = "TOTAL"
res.append(TOTAL.T)

,A l'arret,Achevée,En cours,Gelée,N L,TOTAL OP,A l'arret,Achevée,En cours,Gelée,N L,SUM
Mo,,,,,,,,,,,,
CFORETS,0,7,3,9,2,21,0,415150000,97200000,406500000,5900000,924750000
DAL,0,16,2,8,0,26,0,1597900000,1328720000,3638000000,0,6564620000
DAS,0,2,0,0,0,2,0,10400000,0,0,0,10400000
DCOM,0,2,0,1,0,3,0,75000000,0,210600000,0,285600000
DCUL,0,1,9,7,0,17,0,187000000,1870400000,1068000000,0,3125400000
DENVI,1,0,0,2,0,3,130000000,0,0,280000000,0,410000000
DEP,0,122,27,16,59,224,0,13345748000,14597552000,5621500000,10376460000,43941260000
DEW,0,25,10,0,11,46,0,271900000,438500000,0,148150000,858550000
DFP,0,5,8,10,0,23,0,273000000,1959625000,1822000000,0,4054625000
DIM,0,0,0,1,1,2,0,0,0,55000000,3000000,58000000
DIMP,0,3,1,0,0,4,0,342889000,210000000,0,0,552889000
DJS,1,7,2,28,0,38,335000000,573456000,288000000,1823293000,0,3019749000
DPCIV,0,0,0,1,0,1,0,0,0,120000000,0,120000000
DRE,2,20,16,6,2,46,1160000000,3014300000,4455000000,2290000000,370000000,11289300000
DSA,0,0,2,1,0,3,0,0,49500000,46000000,0,95500000
DSP,2,19,20,0,4,45,223000000,2407400000,4459690000,0,499700000,7589790000
DTMA,0,1,3,3,0,7,0,72000000,550000000,26500000,0,648500000
DTP,0,1,5,0,0,6,0,300000000,3150000000,0,0,3450000000
DTR,0,2,1,3,0,6,0,985167000,104000000,42416000,0,1131583000
DUAC,1,1,2,0,1,5,3000000000,215600000,1000000000,0,200000000,4415600000
TOTAL,7,234,111,96,80,528,4848000000,24086910000,34558187000,17449809000,11603210000,92546116000

In [12]:
res.set_axis(["NOP A l'Arret", "NOP Achevée", "NOP En Course", "NOP Gelée", "NOP Non Lancée", "TOTAL OP", "TOTAL A l'Arret", "TOTAL Achevée", "TOTAL En Cours","TOTAL Gelée", "TOTAL Non Lancée", "SUM"], axis=1, inplace=np.True_)
res

,NOP A l'Arret,NOP Achevée,NOP En Course,NOP Gelée,NOP Non Lancée,TOTAL OP,TOTAL A l'Arret,TOTAL Achevée,TOTAL En Cours,TOTAL Gelée,TOTAL Non Lancée,SUM
Mo,,,,,,,,,,,,
CFORETS,0,7,3,9,2,21,0,415150000,97200000,406500000,5900000,924750000
DAL,0,16,2,8,0,26,0,1597900000,1328720000,3638000000,0,6564620000
DAS,0,2,0,0,0,2,0,10400000,0,0,0,10400000
DCOM,0,2,0,1,0,3,0,75000000,0,210600000,0,285600000
DCUL,0,1,9,7,0,17,0,187000000,1870400000,1068000000,0,3125400000
DENVI,1,0,0,2,0,3,130000000,0,0,280000000,0,410000000
DEP,0,122,27,16,59,224,0,13345748000,14597552000,5621500000,10376460000,43941260000
DEW,0,25,10,0,11,46,0,271900000,438500000,0,148150000,858550000
DFP,0,5,8,10,0,23,0,273000000,1959625000,1822000000,0,4054625000
DIM,0,0,0,1,1,2,0,0,0,55000000,3000000,58000000
DIMP,0,3,1,0,0,4,0,342889000,210000000,0,0,552889000
DJS,1,7,2,28,0,38,335000000,573456000,288000000,1823293000,0,3019749000
DPCIV,0,0,0,1,0,1,0,0,0,120000000,0,120000000
DRE,2,20,16,6,2,46,1160000000,3014300000,4455000000,2290000000,370000000,11289300000
DSA,0,0,2,1,0,3,0,0,49500000,46000000,0,95500000
DSP,2,19,20,0,4,45,223000000,2407400000,4459690000,0,499700000,7589790000
DTMA,0,1,3,3,0,7,0,72000000,550000000,26500000,0,648500000
DTP,0,1,5,0,0,6,0,300000000,3150000000,0,0,3450000000
DTR,0,2,1,3,0,6,0,985167000,104000000,42416000,0,1131583000
DUAC,1,1,2,0,1,5,3000000000,215600000,1000000000,0,200000000,4415600000

In [13]:
DC = res["TOTAL Gelée"] + res["TOTAL Non Lancée"]
DC.name = "Dépenses Cumulées"
DC

Mo
CFORETS     412400000
DAL        3638000000
DAS                 0
DCOM        210600000
DCUL       1068000000
DENVI       280000000
DEP       15997960000
DEW         148150000
DFP        1822000000
DIM          58000000
DIMP                0
DJS        1823293000
DPCIV       120000000
DRE        2660000000
DSA          46000000
DSP         499700000
DTMA         26500000
DTP                 0
DTR          42416000
DUAC        200000000
Name: Dépenses Cumulées, dtype: float64

In [14]:
res = [res, DC]
res = pd.concat(res, axis=1)
res

,NOP A l'Arret,NOP Achevée,NOP En Course,NOP Gelée,NOP Non Lancée,TOTAL OP,TOTAL A l'Arret,TOTAL Achevée,TOTAL En Cours,TOTAL Gelée,TOTAL Non Lancée,SUM,Dépenses Cumulées
Mo,,,,,,,,,,,,,
CFORETS,0,7,3,9,2,21,0,415150000,97200000,406500000,5900000,924750000,412400000
DAL,0,16,2,8,0,26,0,1597900000,1328720000,3638000000,0,6564620000,3638000000
DAS,0,2,0,0,0,2,0,10400000,0,0,0,10400000,0
DCOM,0,2,0,1,0,3,0,75000000,0,210600000,0,285600000,210600000
DCUL,0,1,9,7,0,17,0,187000000,1870400000,1068000000,0,3125400000,1068000000
DENVI,1,0,0,2,0,3,130000000,0,0,280000000,0,410000000,280000000
DEP,0,122,27,16,59,224,0,13345748000,14597552000,5621500000,10376460000,43941260000,15997960000
DEW,0,25,10,0,11,46,0,271900000,438500000,0,148150000,858550000,148150000
DFP,0,5,8,10,0,23,0,273000000,1959625000,1822000000,0,4054625000,1822000000
DIM,0,0,0,1,1,2,0,0,0,55000000,3000000,58000000,58000000
DIMP,0,3,1,0,0,4,0,342889000,210000000,0,0,552889000,0
DJS,1,7,2,28,0,38,335000000,573456000,288000000,1823293000,0,3019749000,1823293000
DPCIV,0,0,0,1,0,1,0,0,0,120000000,0,120000000,120000000
DRE,2,20,16,6,2,46,1160000000,3014300000,4455000000,2290000000,370000000,11289300000,2660000000
DSA,0,0,2,1,0,3,0,0,49500000,46000000,0,95500000,46000000
DSP,2,19,20,0,4,45,223000000,2407400000,4459690000,0,499700000,7589790000,499700000
DTMA,0,1,3,3,0,7,0,72000000,550000000,26500000,0,648500000,26500000
DTP,0,1,5,0,0,6,0,300000000,3150000000,0,0,3450000000,0
DTR,0,2,1,3,0,6,0,985167000,104000000,42416000,0,1131583000,42416000
DUAC,1,1,2,0,1,5,3000000000,215600000,1000000000,0,200000000,4415600000,200000000