In [3]:
import pandas as pd
import mysql.connector as connection
import xlsxwriter as xw

In [4]:
try:
    db = connection.connect(host="localhost", database="DPSB", user="root", password="a21305556699", use_pure=True)
    file = open("../Queries/queries.sql", "r")
    query = file.read()
    df = pd.read_sql(query, db)
    file.close()
    db.close()
except Exception as e:
    db.close()
    file.close()
    print(str(e))
df

,MO,Numéro et intitulé de l'opération,Date d'inscription,AP actuelle,Engagement cumulé,Paiment cumulé,Situation MICL
0,CFORETS,N.E.5.226.2.262.141.18.01\nTravaux sylivicoles,2018-03-12,42000000,2.288443e+07,2.097448e+07,Achevée
1,CFORETS,N.E.5.226.2.262.141.18.03\nAménagement de pist...,2019-05-06,60000000,5.900001e+07,3.997745e+07,En cours
2,CFORETS,N.E.5.226.2.262.141.18.04\nReboisement en chaê...,2019-05-06,20000000,1.919963e+07,9.948582e+06,Achevée
3,CFORETS,N.E.5.226.2.262.141.20.02\nAménagement de pist...,2020-10-21,22500000,1.363157e+07,8.656179e+06,En cours
4,CFORETS,N.E.5.226.2.262.141.20.03\nTravaux sylvicoles ...,2020-10-21,14700000,5.072494e+06,2.454494e+06,En cours
...,...,...,...,...,...,...,...
323,DTR,S.F.5.512.2.262.141.06.02\nEtude et réalisatio...,2007-01-30,104000000,9.802180e+07,6.467180e+07,En cours
324,DTR,"N.F.5.512.2.262.141.10.01\nEtude, réalisation ...",2010-03-22,879167000,7.443311e+08,7.164944e+08,Achevée
325,DUAC,N.E.5.176.3.262.141.18.01\nRéalisation d'une z...,2019-02-13,3000000000,2.680570e+09,9.571362e+08,A l'arret
326,DUAC,S.E.5.721.1.262.141.18.01\nTravaux de V.R.D de...,2019-09-03,500000000,1.290458e+08,9.896016e+06,En cours
327,DUAC,S.E.5.721.1.262.141.18.02\nTravaux de V.R.D de...,2019-12-11,500000000,3.008152e+08,1.270199e+06,En cours

In [5]:
df.to_excel("/home/zuhir/Documents/synthesis.xlsx")

In [7]:

startCells = [1]
for row in range(2,len(df)+1):
    if (df.loc[row-1,'MO'] != df.loc[row-2,'MO']):
        startCells.append(row)
writer = pd.ExcelWriter('/home/zuhir/Documents/synthesis.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name='Sheet1', index=False)
workbook = writer.book
worksheet = writer.sheets['Sheet1']
merge_format = workbook.add_format({'align': 'center', 'valign': 'vcenter', 'border': 2})


lastRow = len(df)

for row in startCells:
    try:
        endRow = startCells[startCells.index(row)+1]-1
        if row == endRow:
            worksheet.write(row, 0, df.loc[row-1,'MO'], merge_format)
        else:
            worksheet.merge_range(row, 0, endRow, 0, df.loc[row-1,'MO'], merge_format)
    except IndexError:
        if row == lastRow:
            worksheet.write(row, 0, df.loc[row-1,'MO'], merge_format)
        else:
            worksheet.merge_range(row, 0, lastRow, 0, df.loc[row-1,'MO'], merge_format)
writer.save()