In [47]:
import mysql.connector as connection
import pandas as pd
import numpy as np

In [48]:
try:
    db = connection.connect(host="localhost", database="DPSB", user="root", password="a21305556699", use_pure=True)
    query = "SELECT Mo, MICL, COUNT(MO) as Number, SUM(APA) + SUM(API) as SUM FROM UPDATES2 GROUP BY MO, MICL;"
    df = pd.read_sql(query, db)
    db.close()
except Exception as e:
    db.close()
    print(str(e))

In [49]:
df

        Mo       MICL  Number         SUM
0      CFr    Achevée       7   760505000
1      CFr   En cours       3   194400000
2      CFr      Gelée       9   813000000
3      CFr        N L       2    11800000
4      DAL    Achevée      16  2294900000
5      DAL   En cours       2  1757440000
6      DAL      Gelée       8  6364000000
7      DAS    Achevée       2    20400000
8     DCmr    Achevée       2   150000000
9     DCmr      Gelée       1   421200000
10  Dcultr    Achevée       1   337000000
11  Dcultr   En cours       8  2837400000
12  Dcultr      Gelée       7  2136000000
13  Dcultr        N L       1    80000000
14    DEDU    Achevée      25   768800000
15    DEDU   En cours      10   877000000
16    DEDU        N L      11   295400000
17   DEnvr  A l'arret       1   160000000
18   DEnvr      Gelée       2   460000000
19     DEP    Achevée     122 21391851000
20     DEP   En cours      24 22701252000
21     DEP      Gelée      16  8569500000
22     DEP        N L      62 18853820000
23     DFP    Achevée       5   482000000
24     DFP   En cours       8  2769250000
25     DFP      Gelée      10  2865000000
26      DI    Achevée       3   528389000
27      DI   En cours       1   370000000
28     DIM      Gelée       1   105000000
29     DIM        N L       1     6000000
30     DJS  A l'arret       1   385000000
31     DJS    Achevée       7   973456000
32     DJS   En cours       2   428000000
33     DJS      Gelée      28  3521731000
34     DPc      Gelée       1   240000000
35     DRE  A l'arret       2  2120000000
36     DRE    Achevée      20  5911300000
37     DRE   En cours      16  8488000000
38     DRE      Gelée       6  4400000000
39     DRE        N L       2   740000000
40     DSA   En cours       2    92500000
41     DSA      Gelée       1    92000000
42     DSP  A l'arret       1   260000000
43     DSP    Achevée      19  3873400000
44     DSP   En cours      20  7162380000
45     DSP        N L       5  1119400000
46     DTP    Achevée       1   600000000
47     DTP   En cours       3  4100000000
48     DTP        N L       2  1600000000
49   DTrsm    Achevée       1   122000000
50   DTrsm   En cours       3  1100000000
51   DTrsm      Gelée       3    53000000
52   DTrsp    Achevée       2  1554334000
53   DTrsp      Gelée       4   208832000
54    duac  A l'arret       1  6000000000
55    duac    Achevée       1   365600000
56    duac   En cours       2  2000000000

In [50]:
res = df.pivot(index="Mo", columns="MICL", values=["Number", "SUM"])

In [51]:
pd.set_option('display.float_format', lambda x: '%.0f' % x)
res = res.replace(np.nan, 0)

In [52]:
res

          Number                                   SUM              \
MICL   A l'arret Achevée En cours Gelée N L  A l'arret     Achevée
Mo
CFr            0       7        3     9   2          0   760505000
DAL            0      16        2     8   0          0  2294900000
DAS            0       2        0     0   0          0    20400000
DCmr           0       2        0     1   0          0   150000000
DEDU           0      25       10     0  11          0   768800000
DEP            0     122       24    16  62          0 21391851000
DEnvr          1       0        0     2   0  160000000           0
DFP            0       5        8    10   0          0   482000000
DI             0       3        1     0   0          0   528389000
DIM            0       0        0     1   1          0           0
DJS            1       7        2    28   0  385000000   973456000
DPc            0       0        0     1   0          0           0
DRE            2      20       16     6   2 2120000000  5911300000
DSA            0       0        2     1   0          0           0
DSP            1      19       20     0   5  260000000  3873400000
DTP            0       1        3     0   2          0   600000000
DTrsm          0       1        3     3   0          0   122000000
DTrsp          0       2        0     4   0          0  1554334000
Dcultr         0       1        8     7   1          0   337000000
duac           1       1        2     0   0 6000000000   365600000


MICL      En cours      Gelée         N L
Mo
CFr      194400000  813000000    11800000
DAL     1757440000 6364000000           0
DAS              0          0           0
DCmr             0  421200000           0
DEDU     877000000          0   295400000
DEP    22701252000 8569500000 18853820000
DEnvr            0  460000000           0
DFP     2769250000 2865000000           0
DI       370000000          0           0
DIM              0  105000000     6000000
DJS      428000000 3521731000           0
DPc              0  240000000           0
DRE     8488000000 4400000000   740000000
DSA       92500000   92000000           0
DSP     7162380000          0  1119400000
DTP     4100000000          0  1600000000
DTrsm   1100000000   53000000           0
DTrsp            0  208832000           0
Dcultr  2837400000 2136000000    80000000
duac    2000000000          0           0

In [53]:
TOTAL_OP = res["Number"].sum(axis=1)
TOTAL_OP.name = "TOTAL OP"
Number = [res["Number"], TOTAL_OP]
Number = pd.concat(Number, axis=1)
Number

        A l'arret  Achevée  En cours  Gelée  N L  TOTAL OP
Mo
CFr             0        7         3      9    2        21
DAL             0       16         2      8    0        26
DAS             0        2         0      0    0         2
DCmr            0        2         0      1    0         3
DEDU            0       25        10      0   11        46
DEP             0      122        24     16   62       224
DEnvr           1        0         0      2    0         3
DFP             0        5         8     10    0        23
DI              0        3         1      0    0         4
DIM             0        0         0      1    1         2
DJS             1        7         2     28    0        38
DPc             0        0         0      1    0         1
DRE             2       20        16      6    2        46
DSA             0        0         2      1    0         3
DSP             1       19        20      0    5        45
DTP             0        1         3      0    2         6
DTrsm           0        1         3      3    0         7
DTrsp           0        2         0      4    0         6
Dcultr          0        1         8      7    1        17
duac            1        1         2      0    0         4

In [54]:
TOTAL_SUM = res["SUM"].sum(axis=1)
TOTAL_SUM.name = "SUM"
SUM = [res["SUM"], TOTAL_SUM]
SUM = pd.concat(SUM, axis=1)
SUM

        A l'arret     Achevée    En cours      Gelée         N L         SUM
Mo
CFr             0   760505000   194400000  813000000    11800000  1779705000
DAL             0  2294900000  1757440000 6364000000           0 10416340000
DAS             0    20400000           0          0           0    20400000
DCmr            0   150000000           0  421200000           0   571200000
DEDU            0   768800000   877000000          0   295400000  1941200000
DEP             0 21391851000 22701252000 8569500000 18853820000 71516423000
DEnvr   160000000           0           0  460000000           0   620000000
DFP             0   482000000  2769250000 2865000000           0  6116250000
DI              0   528389000   370000000          0           0   898389000
DIM             0           0           0  105000000     6000000   111000000
DJS     385000000   973456000   428000000 3521731000           0  5308187000
DPc             0           0           0  240000000           0   240000000
DRE    2120000000  5911300000  8488000000 4400000000   740000000 21659300000
DSA             0           0    92500000   92000000           0   184500000
DSP     260000000  3873400000  7162380000          0  1119400000 12415180000
DTP             0   600000000  4100000000          0  1600000000  6300000000
DTrsm           0   122000000  1100000000   53000000           0  1275000000
DTrsp           0  1554334000           0  208832000           0  1763166000
Dcultr          0   337000000  2837400000 2136000000    80000000  5390400000
duac   6000000000   365600000  2000000000          0           0  8365600000

In [55]:
res = [Number, SUM]
res = pd.concat(res, axis=1)
res

,A l'arret,Achevée,En cours,Gelée,N L,TOTAL OP,A l'arret,Achevée,En cours,Gelée,N L,SUM
Mo,,,,,,,,,,,,
CFr,0,7,3,9,2,21,0,760505000,194400000,813000000,11800000,1779705000
DAL,0,16,2,8,0,26,0,2294900000,1757440000,6364000000,0,10416340000
DAS,0,2,0,0,0,2,0,20400000,0,0,0,20400000
DCmr,0,2,0,1,0,3,0,150000000,0,421200000,0,571200000
DEDU,0,25,10,0,11,46,0,768800000,877000000,0,295400000,1941200000
DEP,0,122,24,16,62,224,0,21391851000,22701252000,8569500000,18853820000,71516423000
DEnvr,1,0,0,2,0,3,160000000,0,0,460000000,0,620000000
DFP,0,5,8,10,0,23,0,482000000,2769250000,2865000000,0,6116250000
DI,0,3,1,0,0,4,0,528389000,370000000,0,0,898389000
DIM,0,0,0,1,1,2,0,0,0,105000000,6000000,111000000
DJS,1,7,2,28,0,38,385000000,973456000,428000000,3521731000,0,5308187000
DPc,0,0,0,1,0,1,0,0,0,240000000,0,240000000
DRE,2,20,16,6,2,46,2120000000,5911300000,8488000000,4400000000,740000000,21659300000
DSA,0,0,2,1,0,3,0,0,92500000,92000000,0,184500000
DSP,1,19,20,0,5,45,260000000,3873400000,7162380000,0,1119400000,12415180000
DTP,0,1,3,0,2,6,0,600000000,4100000000,0,1600000000,6300000000
DTrsm,0,1,3,3,0,7,0,122000000,1100000000,53000000,0,1275000000
DTrsp,0,2,0,4,0,6,0,1554334000,0,208832000,0,1763166000
Dcultr,0,1,8,7,1,17,0,337000000,2837400000,2136000000,80000000,5390400000
duac,1,1,2,0,0,4,6000000000,365600000,2000000000,0,0,8365600000

In [56]:
TOTAL = res.sum(axis=0)
TOTAL

A l'arret              6
Achevée              234
En cours             104
Gelée                 97
N L                   86
TOTAL OP             527
A l'arret     8925000000
Achevée      40133935000
En cours     54877622000
Gelée        30249263000
N L          22706420000
SUM         156892240000
dtype: float64

In [57]:
TOTAL.name = "TOTAL"
res.append(TOTAL.T)

,A l'arret,Achevée,En cours,Gelée,N L,TOTAL OP,A l'arret,Achevée,En cours,Gelée,N L,SUM
Mo,,,,,,,,,,,,
CFr,0,7,3,9,2,21,0,760505000,194400000,813000000,11800000,1779705000
DAL,0,16,2,8,0,26,0,2294900000,1757440000,6364000000,0,10416340000
DAS,0,2,0,0,0,2,0,20400000,0,0,0,20400000
DCmr,0,2,0,1,0,3,0,150000000,0,421200000,0,571200000
DEDU,0,25,10,0,11,46,0,768800000,877000000,0,295400000,1941200000
DEP,0,122,24,16,62,224,0,21391851000,22701252000,8569500000,18853820000,71516423000
DEnvr,1,0,0,2,0,3,160000000,0,0,460000000,0,620000000
DFP,0,5,8,10,0,23,0,482000000,2769250000,2865000000,0,6116250000
DI,0,3,1,0,0,4,0,528389000,370000000,0,0,898389000
DIM,0,0,0,1,1,2,0,0,0,105000000,6000000,111000000
DJS,1,7,2,28,0,38,385000000,973456000,428000000,3521731000,0,5308187000
DPc,0,0,0,1,0,1,0,0,0,240000000,0,240000000
DRE,2,20,16,6,2,46,2120000000,5911300000,8488000000,4400000000,740000000,21659300000
DSA,0,0,2,1,0,3,0,0,92500000,92000000,0,184500000
DSP,1,19,20,0,5,45,260000000,3873400000,7162380000,0,1119400000,12415180000
DTP,0,1,3,0,2,6,0,600000000,4100000000,0,1600000000,6300000000
DTrsm,0,1,3,3,0,7,0,122000000,1100000000,53000000,0,1275000000
DTrsp,0,2,0,4,0,6,0,1554334000,0,208832000,0,1763166000
Dcultr,0,1,8,7,1,17,0,337000000,2837400000,2136000000,80000000,5390400000
duac,1,1,2,0,0,4,6000000000,365600000,2000000000,0,0,8365600000
TOTAL,6,234,104,97,86,527,8925000000,40133935000,54877622000,30249263000,22706420000,156892240000

In [58]:
res.set_axis(["NOP A l'Arret", "NOP Achevée", "NOP En Course", "NOP Gelée", "NOP Non Lancée", "TOTAL OP", "TOTAL A l'Arret", "TOTAL Achevée", "TOTAL En Cours","TOTAL Gelée", "TOTAL Non Lancée", "SUM"], axis=1, inplace=np.True_)
res

,NOP A l'Arret,NOP Achevée,NOP En Course,NOP Gelée,NOP Non Lancée,TOTAL OP,TOTAL A l'Arret,TOTAL Achevée,TOTAL En Cours,TOTAL Gelée,TOTAL Non Lancée,SUM
Mo,,,,,,,,,,,,
CFr,0,7,3,9,2,21,0,760505000,194400000,813000000,11800000,1779705000
DAL,0,16,2,8,0,26,0,2294900000,1757440000,6364000000,0,10416340000
DAS,0,2,0,0,0,2,0,20400000,0,0,0,20400000
DCmr,0,2,0,1,0,3,0,150000000,0,421200000,0,571200000
DEDU,0,25,10,0,11,46,0,768800000,877000000,0,295400000,1941200000
DEP,0,122,24,16,62,224,0,21391851000,22701252000,8569500000,18853820000,71516423000
DEnvr,1,0,0,2,0,3,160000000,0,0,460000000,0,620000000
DFP,0,5,8,10,0,23,0,482000000,2769250000,2865000000,0,6116250000
DI,0,3,1,0,0,4,0,528389000,370000000,0,0,898389000
DIM,0,0,0,1,1,2,0,0,0,105000000,6000000,111000000
DJS,1,7,2,28,0,38,385000000,973456000,428000000,3521731000,0,5308187000
DPc,0,0,0,1,0,1,0,0,0,240000000,0,240000000
DRE,2,20,16,6,2,46,2120000000,5911300000,8488000000,4400000000,740000000,21659300000
DSA,0,0,2,1,0,3,0,0,92500000,92000000,0,184500000
DSP,1,19,20,0,5,45,260000000,3873400000,7162380000,0,1119400000,12415180000
DTP,0,1,3,0,2,6,0,600000000,4100000000,0,1600000000,6300000000
DTrsm,0,1,3,3,0,7,0,122000000,1100000000,53000000,0,1275000000
DTrsp,0,2,0,4,0,6,0,1554334000,0,208832000,0,1763166000
Dcultr,0,1,8,7,1,17,0,337000000,2837400000,2136000000,80000000,5390400000
duac,1,1,2,0,0,4,6000000000,365600000,2000000000,0,0,8365600000

In [59]:
DC = res["TOTAL Gelée"] + res["TOTAL Non Lancée"]
DC.name = "Dépenses Cumulées"
DC

Mo
CFr        824800000
DAL       6364000000
DAS                0
DCmr       421200000
DEDU       295400000
DEP      27423320000
DEnvr      460000000
DFP       2865000000
DI                 0
DIM        111000000
DJS       3521731000
DPc        240000000
DRE       5140000000
DSA         92000000
DSP       1119400000
DTP       1600000000
DTrsm       53000000
DTrsp      208832000
Dcultr    2216000000
duac               0
Name: Dépenses Cumulées, dtype: float64

In [60]:
res = [res, DC]
res = pd.concat(res, axis=1)
res

,NOP A l'Arret,NOP Achevée,NOP En Course,NOP Gelée,NOP Non Lancée,TOTAL OP,TOTAL A l'Arret,TOTAL Achevée,TOTAL En Cours,TOTAL Gelée,TOTAL Non Lancée,SUM,Dépenses Cumulées
Mo,,,,,,,,,,,,,
CFr,0,7,3,9,2,21,0,760505000,194400000,813000000,11800000,1779705000,824800000
DAL,0,16,2,8,0,26,0,2294900000,1757440000,6364000000,0,10416340000,6364000000
DAS,0,2,0,0,0,2,0,20400000,0,0,0,20400000,0
DCmr,0,2,0,1,0,3,0,150000000,0,421200000,0,571200000,421200000
DEDU,0,25,10,0,11,46,0,768800000,877000000,0,295400000,1941200000,295400000
DEP,0,122,24,16,62,224,0,21391851000,22701252000,8569500000,18853820000,71516423000,27423320000
DEnvr,1,0,0,2,0,3,160000000,0,0,460000000,0,620000000,460000000
DFP,0,5,8,10,0,23,0,482000000,2769250000,2865000000,0,6116250000,2865000000
DI,0,3,1,0,0,4,0,528389000,370000000,0,0,898389000,0
DIM,0,0,0,1,1,2,0,0,0,105000000,6000000,111000000,111000000
DJS,1,7,2,28,0,38,385000000,973456000,428000000,3521731000,0,5308187000,3521731000
DPc,0,0,0,1,0,1,0,0,0,240000000,0,240000000,240000000
DRE,2,20,16,6,2,46,2120000000,5911300000,8488000000,4400000000,740000000,21659300000,5140000000
DSA,0,0,2,1,0,3,0,0,92500000,92000000,0,184500000,92000000
DSP,1,19,20,0,5,45,260000000,3873400000,7162380000,0,1119400000,12415180000,1119400000
DTP,0,1,3,0,2,6,0,600000000,4100000000,0,1600000000,6300000000,1600000000
DTrsm,0,1,3,3,0,7,0,122000000,1100000000,53000000,0,1275000000,53000000
DTrsp,0,2,0,4,0,6,0,1554334000,0,208832000,0,1763166000,208832000
Dcultr,0,1,8,7,1,17,0,337000000,2837400000,2136000000,80000000,5390400000,2216000000
duac,1,1,2,0,0,4,6000000000,365600000,2000000000,0,0,8365600000,0